image: alpine:edge
variables:
  GIT_URL: git@gitlab.com:$CI_PROJECT_PATH.git
build:
  tags:
    - build
  stage: build
  cache:
    paths:
      - edge
  before_script:
    - apk update
    - apk add alpine-sdk sudo openssh-client
    - adduser -G abuild -D build
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$SSH_GITLAB_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - chown -R build:abuild community/rust
    # - mv $ABUILD_CONF /etc/abuild.conf
    # - echo $REPOSITORY_URL >> /etc/apk/repositories
    # - wget -P /etc/apk/keys $REPOSITORY_KEY_URL
    # - mkdir edge
  script:
    - cd community/rust
    - sudo -u build abuild-keygen -ani
    - sudo -u build abuild checksum
    - sudo -u build abuild -r
    - git checkout $CI_COMMIT_REF_NAME
    - git add APKBUILD
    - git commit -v -a -s --no-edit --amend
    - git checkout master
    - git cherry-pick $CI_COMMIT_REF_NAME
    - git remote set-url origin $GIT_URL
    - git push --force origin master:upgrade/rust
    # - mv /home/build/packages/community /cache/edge
    # - docker build -t rust:alpine --no-cache .
    # - docker run --name rust rust:alpine cat /home/build/rust/APKBUILD > APKBUILD
    # - docker rm rust
    # - git remote set-url origin "https://$GIT_ACCESS_USER:$GIT_ACCESS_PASSWORD@${url_host}"
