image: alpine:edge
variables:
  GIT_URL: git@gitlab.com:$CI_PROJECT_PATH.git
build:
  tags:
    - build
  stage: build
  before_script:
    - apk update
    - apk add alpine-sdk sudo openssh-client
    - adduser -G abuild -D build
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$SSH_GITLAB_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - chown -R build:abuild main/llvm7
  script:
    - cd main/llvm7
    - sudo -u build abuild checksum
    - sudo -u build abuild-keygen -an
    - sudo -u build abuild -r
    - git checkout $CI_COMMIT_REF_NAME
    - git add APKBUILD
    - git commit -v -a -s --no-edit --amend
    - git checkout master
    - git cherry-pick $CI_COMMIT_REF_NAME
    - git remote set-url origin $GIT_URL
    - git push --force origin master:upgrade-llvm
    # - docker build -t rust:alpine --no-cache .
    # - docker run --name rust rust:alpine cat /home/build/rust/APKBUILD > APKBUILD
    # - docker rm rust
    # - git remote set-url origin "https://$GIT_ACCESS_USER:$GIT_ACCESS_PASSWORD@${url_host}"
